### ISSUE TITLE
OIM3690 - Section 01: I am unable to set the X-indexes

### ISSUE THREAD

**Issue by fernandagonzalez10** [OIM3690/resources#1]
Hello Professor, 
I am currently finishing up exercise #5. I am trying to place h3 of "Go beavers" on top of the image with different z-indexes. I currently defined the beaver image as:
 ` }
      div {
        text-align: center;
        position: relative
        left:0px
        top: 4px
        z-index: -1
      }` 

and the header as 

`h3{
        text-align: center;
        position: relative; top: auto; z-index: 1;
      }`

This is under the style section. Additionally, at the bottom of the page I defined the image and header as:

`<div>
      <img src="images/beaver.jpg" alt="Babson Beaver" />
    </div>
    <h3>Go Beavers!</h3>`

When I tried changing the Z-indexes nothing happened. Should I change the relative/absolute part? Or keep playing with the Z-indexes until the text overlays the image? Thank you for your help

**Comment by lzblack** [comment]
I will talk about this tomorrow. One thing you can plan with is `top: auto;` -- try other values.

BTW, this repository is for class materials which is public to all the students. 
- If you want to ask questions about class material or find mistakes in it, you can create issue here.
- If you are asking questions regarding **your own code**, I suggest you create issue in your own repository. 
- If you want to ask questions on **class demo code**, you can create issue in OIM3690/WebTech repository.

I am closing this issue now. Thanks for your understanding.
